# Generated by Django 5.2.1 on 2025-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultcore', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
