# Generated by Django 5.2.1 on 2025-05-17 02:54

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultcore', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
