# Generated by Django 5.2.1 on 2025-05-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultcore', '0007_userprofile_otp_verified_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device',
            field=models.CharField(default='Unknown Device', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
